const PptxGenJS = require('pptxgenjs');
const fs = require('fs');
const path = require('path');

// 创建演示文稿
const pptx = new PptxGenJS({
    name: 'AI辅助编程进入巡航模式',
    author: 'Generated by Claude',
    title: 'AI辅助编程进入巡航模式',
    subject: '三种AI编程方案的对比与实践'
});

// 设置幻灯片尺寸为16:9
pptx.defineLayout({ name:'A4', width:10, height:7.5 });
pptx.layout = 'LAYOUT_WIDE';

// 幻灯片1：标题页
async function addTitleSlide() {
    const slide = pptx.addSlide();
    slide.addText('AI辅助编程进入巡航模式', {
        x: 1,
        y: 2,
        w: 8,
        h: 1.5,
        fontSize: 44,
        bold: true,
        color: 'FFFFFF',
        align: 'center',
        fontFace: 'Arial'
    });
    
    slide.addText('三种AI编程方案的对比与实践', {
        x: 1,
        y: 3.5,
        w: 8,
        h: 0.8,
        fontSize: 24,
        color: 'FE4447',
        align: 'center',
        fontFace: 'Arial'
    });
    
    // 背景色
    slide.background = { color: '1C2833' };
}

// 幻灯片2：三种方案对比
async function addComparisonSlide() {
    const slide = pptx.addSlide();
    
    slide.addText('同一个任务，3种不同的尝试', {
        x: 0.5,
        y: 0.5,
        w: 9,
        h: 1,
        fontSize: 32,
        bold: true,
        color: 'FFFFFF',
        fontFace: 'Arial'
    });
    
    // 方案一
    slide.addText('方案一：Claude Code + GLM4.6', {
        x: 0.5,
        y: 1.8,
        w: 3,
        h: 0.6,
        fontSize: 18,
        bold: true,
        color: 'FE4447',
        fontFace: 'Arial'
    });
    
    slide.addText('• task-master-ai, software-planning-tools, +mcp\n• GLM4.6规划能力OK，代码生成能力偏弱\n• 需要配置skills，结合agent\n• 手工执行workflow\n\n用时：1-2周\n费用：GLM4.6包月60元', {
        x: 0.5,
        y: 2.4,
        w: 3,
        h: 3,
        fontSize: 14,
        color: 'FFFFFF',
        fontFace: 'Arial',
        valign: 'top'
    });
    
    // 方案二
    slide.addText('方案二：Antigravity + Gemini3-Pro', {
        x: 3.5,
        y: 1.8,
        w: 3,
        h: 0.6,
        fontSize: 18,
        bold: true,
        color: 'FE4447',
        fontFace: 'Arial'
    });
    
    slide.addText('• Sonnet4.5\n• 无需配置agent\n• 自动启用MCP\n• 体验丝滑\n\n用时：4小时', {
        x: 3.5,
        y: 2.4,
        w: 3,
        h: 3,
        fontSize: 14,
        color: 'FFFFFF',
        fontFace: 'Arial',
        valign: 'top'
    });
    
    // 方案三
    slide.addText('方案三：Auto-coder + Deepseek3.2', {
        x: 6.5,
        y: 1.8,
        w: 3,
        h: 0.6,
        fontSize: 18,
        bold: true,
        color: 'FE4447',
        fontFace: 'Arial'
    });
    
    slide.addText('• +workflow +agent\n\n用时：2天\n成本：24.59元', {
        x: 6.5,
        y: 2.4,
        w: 3,
        h: 3,
        fontSize: 14,
        color: 'FFFFFF',
        fontFace: 'Arial',
        valign: 'top'
    });
    
    slide.background = { color: '1C2833' };
}

// 幻灯片3：什么任务？
async function addTaskSlide() {
    const slide = pptx.addSlide();
    
    slide.addText('什么任务？', {
        x: 0.5,
        y: 0.5,
        w: 6,
        h: 1,
        fontSize: 32,
        bold: true,
        color: 'FFFFFF',
        fontFace: 'Arial'
    });
    
    slide.addText('Vue-CopilotKit 升级项目', {
        x: 0.5,
        y: 1.8,
        w: 8,
        h: 0.8,
        fontSize: 22,
        bold: true,
        color: '5EA8A7',
        fontFace: 'Arial'
    });
    
    slide.addText('主线需求：', {
        x: 0.5,
        y: 2.8,
        w: 2,
        h: 0.5,
        fontSize: 18,
        bold: true,
        color: 'FE4447',
        fontFace: 'Arial'
    });
    
    slide.addText('Vue-CopilotKit需要升级到与React新版兼容', {
        x: 2.5,
        y: 2.8,
        w: 6,
        h: 0.5,
        fontSize: 16,
        color: 'FFFFFF',
        fontFace: 'Arial'
    });
    
    slide.addText('支线需求：', {
        x: 0.5,
        y: 3.5,
        w: 2,
        h: 0.5,
        fontSize: 18,
        bold: true,
        color: 'FE4447',
        fontFace: 'Arial'
    });
    
    slide.addText('后端接口也修改了，之前很呆板，现在可以换模型，后端可以做更多的事情了', {
        x: 2.5,
        y: 3.5,
        w: 6,
        h: 0.8,
        fontSize: 16,
        color: 'FFFFFF',
        fontFace: 'Arial'
    });
    
    slide.background = { color: '1C2833' };
}

// 添加图片的辅助函数
function addImageToSlide(slide, imagePath, x, y, w, h) {
    if (fs.existsSync(imagePath)) {
        slide.addImage({
            path: imagePath,
            x: x,
            y: y,
            w: w,
            h: h
        });
    }
}

// 幻灯片4：如何做 - 目录结构
async function addHowToSlide1() {
    const slide = pptx.addSlide();
    
    slide.addText('如何做？', {
        x: 0.5,
        y: 0.5,
        w: 4,
        h: 1,
        fontSize: 32,
        bold: true,
        color: 'FFFFFF',
        fontFace: 'Arial'
    });
    
    slide.addText('1、设计目录结构', {
        x: 0.5,
        y: 1.8,
        w: 4,
        h: 0.6,
        fontSize: 20,
        bold: true,
        color: '5EA8A7',
        fontFace: 'Arial'
    });
    
    slide.addText('三个目录的好处：\n• 提供足够上下文\n• 出方案有明确参考\n• Debug有前后端代码', {
        x: 0.5,
        y: 2.4,
        w: 3.5,
        h: 1.5,
        fontSize: 14,
        color: 'FFFFFF',
        fontFace: 'Arial',
        valign: 'top'
    });
    
    // 添加图片
    addImageToSlide(slide, 'image7.png', 4.5, 1.8, 4.5, 3);
    
    slide.background = { color: '1C2833' };
}

// 幻灯片5：项目初始化与配置
async function addConfigSlide() {
    const slide = pptx.addSlide();
    
    slide.addText('项目初始化与配置', {
        x: 0.5,
        y: 0.5,
        w: 6,
        h: 1,
        fontSize: 32,
        bold: true,
        color: 'FFFFFF',
        fontFace: 'Arial'
    });
    
    // CLAUDE.md配置
    slide.addText('CLAUDE.md 配置', {
        x: 0.5,
        y: 1.8,
        w: 3,
        h: 0.5,
        fontSize: 18,
        bold: true,
        color: 'FE4447',
        fontFace: 'Arial'
    });
    addImageToSlide(slide, 'image8.png', 0.5, 2.3, 3, 2);
    
    // AutoCoder RULES.md
    slide.addText('AutoCoder RULES.md', {
        x: 4,
        y: 1.8,
        w: 3,
        h: 0.5,
        fontSize: 18,
        bold: true,
        color: 'FE4447',
        fontFace: 'Arial'
    });
    addImageToSlide(slide, 'image9.png', 4, 2.3, 3, 1);
    
    // Antigravity配置
    slide.addText('Antigravity 配置', {
        x: 4,
        y: 3.5,
        w: 3,
        h: 0.5,
        fontSize: 18,
        bold: true,
        color: 'FE4447',
        fontFace: 'Arial'
    });
    addImageToSlide(slide, 'image10.png', 4, 4, 3, 1);
    
    slide.background = { color: '1C2833' };
}

// 幻灯片6：更多截图展示
async function addScreenshotsSlide() {
    const slide = pptx.addSlide();
    
    slide.addText('项目实践截图', {
        x: 0.5,
        y: 0.5,
        w: 4,
        h: 1,
        fontSize: 32,
        bold: true,
        color: 'FFFFFF',
        fontFace: 'Arial'
    });
    
    // 2x3网格布局展示图片
    addImageToSlide(slide, 'image1.png', 0.5, 1.8, 3, 1.5);
    addImageToSlide(slide, 'image2.png', 4, 1.8, 3, 1.5);
    addImageToSlide(slide, 'image3.png', 7.5, 1.8, 3, 1.5);
    
    addImageToSlide(slide, 'image4.png', 0.5, 3.5, 3, 1.5);
    addImageToSlide(slide, 'image5.png', 4, 3.5, 3, 1.5);
    addImageToSlide(slide, 'image6.png', 7.5, 3.5, 3, 1.5);
    
    slide.background = { color: '1C2833' };
}

// 幻灯片7：总结与反思
async function addSummarySlide() {
    const slide = pptx.addSlide();
    
    slide.addText('总结与反思', {
        x: 0.5,
        y: 0.5,
        w: 4,
        h: 1,
        fontSize: 32,
        bold: true,
        color: 'FFFFFF',
        fontFace: 'Arial'
    });
    
    slide.addText('"好的开始，是成功的一半。"', {
        x: 0.5,
        y: 2,
        w: 9,
        h: 1,
        fontSize: 28,
        bold: true,
        color: '5EA8A7',
        align: 'center',
        fontFace: 'Arial'
    });
    
    slide.addText('当大家学习这种半自动编程时（一次提示，然后可以跑1个小时以上？），\n最难的并不是后面解决问题，而是前面如何初始化项目，\n如何让AI做正确的规划。', {
        x: 0.5,
        y: 3.2,
        w: 9,
        h: 1.5,
        fontSize: 18,
        color: 'FFFFFF',
        align: 'center',
        fontFace: 'Arial'
    });
    
    slide.background = { color: '1C2833' };
}

// 幻灯片8：未来已来
async function addFutureSlide() {
    const slide = pptx.addSlide();
    
    slide.addText('未来已来', {
        x: 0.5,
        y: 0.5,
        w: 3,
        h: 1,
        fontSize: 32,
        bold: true,
        color: 'FFFFFF',
        fontFace: 'Arial'
    });
    
    slide.addText('坏消息：', {
        x: 0.5,
        y: 1.8,
        w: 1.5,
        h: 0.5,
        fontSize: 20,
        bold: true,
        color: 'E74C3C',
        fontFace: 'Arial'
    });
    
    slide.addText('AI辅助编程对前端的挑战非常大', {
        x: 2,
        y: 1.8,
        w: 7,
        h: 0.5,
        fontSize: 18,
        color: 'FFFFFF',
        fontFace: 'Arial'
    });
    
    slide.addText('好消息：', {
        x: 0.5,
        y: 2.5,
        w: 1.5,
        h: 0.5,
        fontSize: 20,
        bold: true,
        color: '2ECC71',
        fontFace: 'Arial'
    });
    
    slide.addText('灵光这类LLM结果动态渲染的AI应用已经开始崭露头角', {
        x: 2,
        y: 2.5,
        w: 7,
        h: 0.5,
        fontSize: 18,
        color: 'FFFFFF',
        fontFace: 'Arial'
    });
    
    slide.addText('AI应用的前端在输入和输出上都会变得足够复杂，这是一条希望之路。\nVue-CopilotKit部分支持动态渲染，还需要进一步增强。', {
        x: 0.5,
        y: 3.5,
        w: 9,
        h: 1,
        fontSize: 16,
        color: 'AAB7B8',
        fontFace: 'Arial',
        valign: 'top'
    });
    
    slide.background = { color: '1C2833' };
}

// 生成所有幻灯片
async function generatePresentation() {
    await addTitleSlide();
    await addComparisonSlide();
    await addTaskSlide();
    await addHowToSlide1();
    await addConfigSlide();
    await addScreenshotsSlide();
    await addSummarySlide();
    await addFutureSlide();
    
    // 保存文件
    pptx.writeFile({ fileName: 'AI辅助编程进入巡航模式.pptx' })
        .then(fileName => {
            console.log('演示文稿已生成:', fileName);
        });
}

// 执行生成
generatePresentation().catch(console.error);